# Generated by Django 5.1.4 on 2024-12-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
