# Generated by Django 5.1.4 on 2025-01-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Оплата", "verbose_name_plural": "Оплаты"},
        ),
    ]
