# Generated by Django 5.1.4 on 2024-12-25 11:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscription",
            new_name="SubscriptionCourse",
        ),
    ]
