# Generated by Django 5.1.4 on 2025-01-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_rename_subscription_subscriptioncourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="сумма покупки"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="сумма покупки"
            ),
        ),
    ]
