# Generated by Django 5.1.6 on 2025-02-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_course_amount_lesson_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.URLField(max_length=515, verbose_name="ссылка на видео"),
        ),
    ]
