# Generated by Django 5.1.6 on 2025-02-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_alter_course_title_alter_lesson_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название"
            ),
        ),
    ]
