# Generated by Django 5.1.6 on 2025-02-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0009_alter_course_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                blank=True, default=" ", max_length=255, verbose_name="Название"
            ),
            preserve_default=False,
        ),
    ]
